In [3]:
from sparql_dataframe import get 

endpoint = 'http://127.0.0.1:9999/blazegraph/sparql' 

query = """
PREFIX res:    <https://github.com/DataScienceProject23-24/DataProject/tree/main/resources/>
PREFIX rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX schema: <https://schema.org/>

SELECT *
WHERE {
    ?s rdf:type schema:Book.
    ?s ?p ?o.
}
"""

df_sparql = get(endpoint, query, True) #True: just do it
df_sparql

                                                    s  ...                                        o
0   https://github.com/DataScienceProject23-24/Dat...  ...                      The Natural History
1   https://github.com/DataScienceProject23-24/Dat...  ...                                      BUB
2   https://github.com/DataScienceProject23-24/Dat...  ...                                        4
3   https://github.com/DataScienceProject23-24/Dat...  ...                                     1519
4   https://github.com/DataScienceProject23-24/Dat...  ...                                  Bologna
5   https://github.com/DataScienceProject23-24/Dat...  ...                  https://schema.org/Book
6   https://github.com/DataScienceProject23-24/Dat...  ...  Natural and Moral History of the Indies
7   https://github.com/DataScienceProject23-24/Dat...  ...                                      BUB
8   https://github.com/DataScienceProject23-24/Dat...  ...                                        8
9   https://github.com/DataScienceProject23-24/Dat...  ...                                     1596
10  https://github.com/DataScienceProject23-24/Dat...  ...                                  Bologna
11  https://github.com/DataScienceProject23-24/Dat...  ...                  https://schema.org/Book
12  https://github.com/DataScienceProject23-24/Dat...  ...                    The History of Plants
13  https://github.com/DataScienceProject23-24/Dat...  ...                                      BUB
14  https://github.com/DataScienceProject23-24/Dat...  ...                                        2
15  https://github.com/DataScienceProject23-24/Dat...  ...                                     1497
16  https://github.com/DataScienceProject23-24/Dat...  ...                                  Bologna
17  https://github.com/DataScienceProject23-24/Dat...  ...                  https://schema.org/Book
18  https://github.com/DataScienceProject23-24/Dat...  ...                         On the New World
19  https://github.com/DataScienceProject23-24/Dat...  ...                                      BUB
20  https://github.com/DataScienceProject23-24/Dat...  ...                                        7
21  https://github.com/DataScienceProject23-24/Dat...  ...                                     1530
22  https://github.com/DataScienceProject23-24/Dat...  ...                                  Bologna
23  https://github.com/DataScienceProject23-24/Dat...  ...                  https://schema.org/Book
24  https://github.com/DataScienceProject23-24/Dat...  ...                                  Cyclops
25  https://github.com/DataScienceProject23-24/Dat...  ...                                      BUB
26  https://github.com/DataScienceProject23-24/Dat...  ...                                       30
27  https://github.com/DataScienceProject23-24/Dat...  ...                                     1642
28  https://github.com/DataScienceProject23-24/Dat...  ...                                  Bologna
29  https://github.com/DataScienceProject23-24/Dat...  ...                  https://schema.org/Book

[30 rows x 3 columns]